baseURL = "https://blog.awalol.eu.org/"
languageCode = "zh-cn"
title = "awalol's Blog"
theme = "PaperMod"

[sitemap]
  changeFreq = ''
  filename = 'sitemap.xml'
  priority = -1
<<<<<<< HEAD

[[menu.main]]
  identifier = "archives"
  name = "Archives"
  url = "/archives/"
  weight = 10

[[menu.main]]
  identifier = "tags"
  name = "Tags"
  url = "/tags/"
  weight = 20

[params]
  ShowCodeCopyButtons = true
  ShowWordCount = true

[params.homeInfoParams]
  Title = "Hi there 👋"
  Content = "Like to do fun things"

[[params.socialIcons]]
  name = "github"
  url = "https://github.com/CNawalol"

[taxonomies]
tag = "tags"
=======
>>>>>>> d7945b5dc88c11bddd6b294065261f6183239b9b
